### ISSUE TITLE
Approving the PR doesn't always reflect the approval in the "Reviewers" area

### ISSUE THREAD

**Issue by henry-bettany** [buildsville/assign-reviewer-by-label#5]
We're using this GitHub Action to assign reviewers to PRs based on the teams they're in. We've got labels for:
* Frontend
* Backend
* DevOps

Several of the team members are in multiple teams, and the person raising the PR will almost always be part of the team(s) they are labelling the PR for.

Our YAML file looks like this:
```
name: Assign Reviewers by Label
on:
  pull_request:
    types:
      - opened
      - unlabeled
      - labeled

jobs:
  assign_frontend:
    runs-on: ubuntu-latest
    name: Assign Frontend Team
    steps:
      - name: Assign Frontend Team
        id: reviewer
        uses: buildsville/assign-reviewer-by-label@v1
        with:
          token: "${{secrets.GITHUB_TOKEN}}"
          labels: '[ "Frontend" ]'
          reviewers: '[ "person1", "person2", "person3"  ]'
  
  assign_backend:
    runs-on: ubuntu-latest
    name: Assign Backend Team
    steps:
      - name: Assign Backend Team
        id: reviewer
        uses: buildsville/assign-reviewer-by-label@v1
        with:
          token: "${{secrets.GITHUB_TOKEN}}"
          labels: '[ "Backend" ]'
          reviewers: '[ "person2", "person4", "person5" ]'
  
  assign_devops:
    runs-on: ubuntu-latest
    name: Assign DevOps Team
    steps:
      - name: Assign DevOps Team
        id: reviewer
        uses: buildsville/assign-reviewer-by-label@v1
        with:
          token: "${{secrets.GITHUB_TOKEN}}"
          labels: '[ "DevOps" ]'
          reviewers: '[ "person1", "person6" ]'
```

The reviewers are added to the PR as expected. However, we've noticed that occasionally, a review has to approve the PR multiple times before the reviewer is shown to have approved the PR in the reviewers' area of the sidebar. GitHub will show in the timeline that the user did approve the PR.

This only started happening after we started to use this GitHub Action. It may well be a GitHub bug, rather than an issue with the action itself, but I was wondering if you'd be able to advise. Thank you.

**Comment by buildsville** [comment]
Hi, thanks to contact!

I tried to reproduce the situation, but unfortunately that situation never happened 😐 
So, following is my guess.

Multiple review requests may have been created for the same person.
However, I do check for duplicates.
Maybe if multiple requests are sent to the github api at exactly the same time, it might have that situation.

So, your github actions setting, it have multiple jobs set up, so the processes are done in parallel.
If you do the following, the steps will be processed in sequential, it will possibly improvement.

```
name: Assign Reviewers by Label
on:
  pull_request:
    types:
      - opened
      - unlabeled
      - labeled

jobs:
  assign_frontend:
    runs-on: ubuntu-latest
    name: Assign Reviewer
    steps:
      - name: Assign Frontend Team
        id: frontend
        uses: buildsville/assign-reviewer-by-label@v1
        with:
          token: "${{secrets.GITHUB_TOKEN}}"
          labels: '[ "Frontend" ]'
          reviewers: '[ "person1", "person2", "person3"  ]'
      - name: Assign Backend Team
        id: backend
        uses: buildsville/assign-reviewer-by-label@v1
        with:
          token: "${{secrets.GITHUB_TOKEN}}"
          labels: '[ "Backend" ]'
          reviewers: '[ "person2", "person4", "person5" ]'
      - name: Assign DevOps Team
        id: devops
        uses: buildsville/assign-reviewer-by-label@v1
        with:
          token: "${{secrets.GITHUB_TOKEN}}"
          labels: '[ "DevOps" ]'
          reviewers: '[ "person1", "person6" ]'
```

Sorry it's not a perfect solution, but you can try if you like.

Thank you 😀
